<?php	
	function fn_histo_cc_chart()
	{				
							include('../../../cnx/database.php');
							$pdo = Database1::connect();
							$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
							$cc=$_GET['cc'];
							$sql = "SELECT  

1 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=12 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=12 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

2 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=11 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=11 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

3 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=10 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=10 AND cc LIKE '%" . $cc . "%' 

UNION 

SELECT  

4 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=9 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=9 AND cc LIKE '%" . $cc . "%' 

UNION 

SELECT  

5 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=8 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=8 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

6 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=7 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=7 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

7 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=6 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'
 
FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=6 AND cc LIKE '%" . $cc . "%' 

UNION 

SELECT  

8 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=5 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=5 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

9 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=4 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=4 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

10 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=3 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=3 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

11 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=2 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=2 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

12 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=1 )) AS label, IFNULL(SUM(CAST(vldec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=1 AND cc LIKE '%" . $cc . "%'

ORDER BY MONTH								  
 ";
				$result = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);
				$return = array();
				foreach ($result as $row1)
				{
				$point=array("label"=>$row1['label']
							,"y"=>$row1['somme']);
				array_push($return, $point); 
				}
				header('Content-type: application/json');
				echo json_encode($return, JSON_NUMERIC_CHECK);
				Database::disconnect();
	}
	
	function fn_histo_cc_chart_nb()
	{				
							include('../../../cnx/database.php');
							$pdo = Database1::connect();
							$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
							$cc=$_GET['cc'];
							$sql = "SELECT  

1 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=12 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=12 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

2 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=11 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=11 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

3 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=10 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=10 AND cc LIKE '%" . $cc . "%' 

UNION 

SELECT  

4 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=9 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=9 AND cc LIKE '%" . $cc . "%' 

UNION 

SELECT  

5 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=8 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=8 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

6 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=7 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=7 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

7 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=6 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'
 
FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=6 AND cc LIKE '%" . $cc . "%' 

UNION 

SELECT  

8 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=5 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=5 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

9 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=4 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=4 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

10 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=3 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=3 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

11 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=2 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=2 AND cc LIKE '%" . $cc . "%'

UNION 

SELECT  

12 AS MONTH,IFNULL(CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)),(SELECT DISTINCT CONCAT(SUBSTRING(MONTHNAME (  DATE ),1,3),'-',YEAR(DATE)) FROM historique 
WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=1 )) AS label, IFNULL(SUM(CAST(nbdec AS DECIMAL(10,0))),0) 'somme'

FROM historique WHERE CASE WHEN MONTH(DATE)<>2 THEN  TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())<=29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),SUBSTRING(NOW(),9,2) ), NOW()) 
WHEN MONTH(DATE)=2 AND DAY(NOW())>29 THEN TIMESTAMPDIFF(MONTH, CONCAT(SUBSTRING(DATE,1,8),'29' ), NOW()) END=1 AND cc LIKE '%" . $cc . "%'

ORDER BY MONTH										  
 ";
				$result = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);
				$return = array();
				foreach ($result as $row1)
				{
				$point=array("label"=>$row1['label']
							,"y"=>$row1['somme']);
				array_push($return, $point); 
				}
				header('Content-type: application/json');
				echo json_encode($return, JSON_NUMERIC_CHECK);
				Database::disconnect();
	}
?>